### ISSUE TITLE
Cannot upload ui5 app

### ISSUE THREAD

**Issue by konbec** [kleferbe/ui5uploader#1]
Hello,
we get a following exception at uploading an ui5 app:

![2016-02-17 17_11_31-auswahlen eingabeaufforderung](https://cloud.githubusercontent.com/assets/17289553/13115838/bcf092aa-d599-11e5-9bb4-6ed7bb272a01.png)

Can you help us?

Thanks!

**Comment by kleferbe** [comment]
Hi!
Thanks for reporting this bug.

You need to have a .Ui5RepositoryUploadParameters file in your project root. The file can contain some settings like
SAPUI5ApplicationName=...
SAPUI5ApplicationPackage=...
SAPUI5ApplicationDescription=...
WorkbenchRequest=...

If you supply all necessary parameters via commandline this file should not be needed. I will fix that soon. As a workaround you can create that file empty and place it in the **parent** folder of WebContent.

**Comment by kleferbe** [comment]
Should be fixed now with [last commit](https://github.com/kleferbe/ui5uploader/commit/d03acb00f665cfcfec374c039884918f870eef77)
